### ISSUE TITLE
Install script not working on raspberry pi 02w running Kali.

### ISSUE THREAD

**Issue by fionnafire** [ekkinox/yai#115]
I was able to install yai on my debian proot install in termux on my phone but the installer script doesn't work on my rpi and I can't figure out why.
![Screenshot_20240828_103536_Termux](https://github.com/user-attachments/assets/8bb63ca2-36eb-4d11-9ae2-48023bae6d2b)

**Comment by ekkinox** [comment]
You can download diectly the binary from here: https://github.com/ekkinox/yai/releases/download/0.6.0/yai_0.6.0_linux_arm64.tar.gz

**Comment by fionnafire** [comment]
Oh yes I did that and forgot to remove this post sorry. I got it working. Thank you.
