### ISSUE TITLE
Add --uninstall flag to the installer

### ISSUE THREAD

**Issue by xplshn** [ekkinox/yai#27]
Please add an uninstall flag into the script.

**Comment by ekkinox** [comment]
See https://github.com/ekkinox/yai/pull/28

**Comment by xplshn** [comment]
Wouldn't be better to have it as a flag? Anyways, great to see, I had to check the install script to check the binary file location haha. Nice project, plans for using ChatGPT as backend, through theb.ai ? Its how TGPT works

**Comment by ekkinox** [comment]
install --uninstall seems very weird to me 🙂 so I created a dedicated uninstall script

For theb.ai, I tried it and results relevance seemed less good, also i would need to refactor the full engine of YAI since OpenAI and Bai doesn't have compatible apis.

Will see what I can do.
