### ISSUE TITLE
yai for blackarch ....

### ISSUE THREAD

**Issue by XxnittanixX** [ekkinox/yai#46]
is the most advanced ai  that can automate pentration testing  and can  develop code  to keep others safe from it

**Comment by XxnittanixX** [comment]
you have signle handedly created the first steps  for many hackers  to implement the use of ai in penetration testing. pat your self on the back.

**Comment by ekkinox** [comment]
Not sure if you're sarcastic 😜 

But let me remind you this:
- yai is NEVER running a command without explicit user validation (see examples on the documentation)
- yai NEVER send command outputs to OpenAI (it just keeps track of questions and resulting commands propositions)

Basically, yai is as harmful as using ChatGPT online and copy pasting the results in your terminal. It's not a tool to help hackers, it's a tool to streamline CLI with AI.

We can't prevent malicious usage unfortunately (in terminal, OpenAI website, etc), but that's clearly not why yai was made.

**Comment by ekkinox** [comment]
Since it's not an issue that could lead to bug fix or enhancement, I close this one.
