### ISSUE TITLE
invalid character 'S' in string escape code

### ISSUE THREAD

**Issue by dillfrescott** [ekkinox/yai#58]
🚀 > change my system to light mode
[error] invalid character 'S' in string escape code

**Comment by ekkinox** [comment]
Is this happening only in this prompt? Or in any prompt? In this case, could you please check that your openAi key is correct?

**Comment by dillfrescott** [comment]
I think it was related to the key. its no longer having the issue. Sorry to bother

**Comment by ekkinox** [comment]
No worries 👍
