### ISSUE TITLE
Problem with my secret key 

### ISSUE THREAD

**Issue by Otis1993x** [ekkinox/yai#98]
I post my key like this "sk-bIXG********************************************LM
S" of course I used the actual code and I used the quotation marks on each side so why is it not accepting my code???

**Comment by ekkinox** [comment]
You should give your key without quotes. If still not working, try another key. Let me know

**Comment by Otis1993x** [comment]
I did exactly what you said to do I enter my entire secret without any quotation marks and it did not work this is what I got from the program.
[settings ok]
             
🚀 > ~/.config/yai.json
[error] error, status code: 401, message: Incorrect API key provided: sk-bIXGB**************************************6XLM. You can find

**Comment by ekkinox** [comment]
It's a 401 error, indicating your key is not valid.

Can you try with a valid key?

**Comment by ekkinox** [comment]
Resolving.
